# Site
name: "Resource Lab"
description: "Intelligent management of resources through technology and the methods of science with human and environmental concern."
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/rlogocopy.png'
favicon: 'assets/images/rlfav.png'
baseurl:
google_analytics: 'UA-46278016-1'
disqus: 'resourcelab'
mailchimp-list: 'https://resourcelab.us20.list-manage.com/subscribe/post?u=e552c6b1e8644f6ad437649af&amp;id=c016c9b81e'

# Authors
authors:
  sal:
    name: Lionardo
    display_name: Lionardo
    gravatar: a89e66bfc54a946279dbfaf29cf46865
    email: lb@resourcelab.dk
    web: https://www.resourcelab.dk
    twitter: https://twitter.com/lionardobayer
    description: "Founder of Resource Lab. Environmentalist interested in using science and technology to solve the most pressing problems facing humanity."
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.resourcelab.dk
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 9
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
